version: "3"

services:
  web:
    build:
      context: ./newsreaderClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
  graphql:
    build:
      context: ./newsreaderGraphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
